name: Docker

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest

    name: Build docker image for REST server

    steps:
      - uses: actions/checkout@v1

      - name: Build & push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: docker/rest-server/Dockerfile
          tag_with_ref: true # refs/head/master will be turned into "latest"
          add_git_labels: true
          repository: bedsheets/rest-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push to GCR
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: docker/rest-server/Dockerfile
          tag_with_ref: true # refs/head/master will be turned into "latest"
          add_git_labels: true
          registry: gcr.io
          repository: bedsheets/rest-server
          username: _json_key
          password: ${{ secrets.GCR_KEYFILE }}
