name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["10.x"] # This should match the oldest target node version, as specified by @types/node in the root package.json

    name: Test on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps and build
        run: |
          node --version
          npm --version
          yarn --version
          yarn install --frozen-lockfile
          yarn build:all
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Run tests
        run: |
          yarn test:all:ci
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
          TEST_SPREADSHEET_ID: ${{ secrets.TEST_SPREADSHEET_ID }}
          GOOGLE_AUTH_CLIENT_EMAIL: ${{ secrets.GOOGLE_AUTH_CLIENT_EMAIL }}
          GOOGLE_AUTH_PRIVATE_KEY: ${{ secrets.GOOGLE_AUTH_PRIVATE_KEY }}
